workflow_details:
  name: "Speedmap Dashboard"
  description: "A dashboard for visualizing speedmap trajectories."
er_client_name:
  data_source:
    name: "mep_dev"
groupers:
  groupers: []
time_range:
  since: "2017-01-01T00:00:00Z"
  until: "2017-03-31T23:59:59Z"
subject_obs:
  subject_group_name: "Ecoscope"
subject_traj:
  trajectory_segment_filter:
    min_length_meters: 0.001
    max_length_meters: 10000.0
    max_time_secs: 21600.0
    min_time_secs: 1.0
    max_speed_kmhr: 10.0
    min_speed_kmhr: 0.0001
base_map_defs:
  base_maps:
    - url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
      opacity: 1.0
    - custom_url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
      custom_opacity: 0.5
      custom_max_zoom: 17
      custom_min_zoom: null
